<?php   if (!isset($_SESSION['userId'])): ?>
    <h1>Запретная зона, доступ только авторизированному пользователю</h1>
    <div class="container__admin">
        <p><a href="/reg_form">Зарегистрироваться</a></p>
        <p>Уже есть аккаунт? <a href="/">Войти</a></p>
    </div>
<?php else: ?>
<h2>Информация выводится из списка файлов</h2>
<button class="button upload"><a  href="/upload">Загрузить еще</a></button>
<table class="table table-bordered">
    <tr>
        <th>Название файла</th>
        <th>Фотография</th>
        <th>Действия</th>
    </tr>
    <?php foreach ($listf as $value) : ?>

    <tr>
        <td><?= $value->about?></td>
        <td><img src="<?= $value->file_name?>" alt="" height="150"></td>
        <td>
            <a href="">Удалить аватарку пользователя</a>
        </td>
    </tr>
    <?php endforeach; ?>
</table>
<?php endif; ?>