<form class="form container" action="/register" method="post" enctype="multipart/form-data"> <!-- form--invalid -->
    <h2>Регистрация нового пользователя</h2>

    <div class="form__item"> <!-- form__item--invalid -->
        <label for="login">Логин*</label>
        <input id="login" type="login" name="new_user[login]" placeholder="Введите логин" value="" maxlength="128"
               required>
    </div>

    <div class="form__item">
        <label for="password">Пароль*</label>
        <input id="password" type="password" name="new_user[user_pass]" placeholder="Введите пароль" value="" required>
    </div>

    <div class="form__item">
        <label for="name">Имя*</label>
        <input id="name" type="text" name="new_user[user_name]" placeholder="Введите имя" value="" maxlength="128"
               required>
    </div>
    <div class="form__item">
        <label for="age">Возраст*</label>
        <input id="age" type="text" name="new_user[user_age]" placeholder="Введите возраст" value="" maxlength="4"
               required>
    </div>

    <div class="form__item">
        <label for="message">Контактные данные*</label>
        <textarea id="message" name="new_user[descript]" placeholder="Напишите несколько слов о себе" maxlength="255"
                  required></textarea>
    </div>
    <div class="form__item form__item--file form__item--last ">
        <label>Аватар</label>
        <div class="preview">
            <button class="preview__remove" type="button">x</button>
            <div class="preview__img">
                <img src="img/avatar.jpg" width="113" height="113" alt="Ваш аватар">
            </div>
        </div>
        <div class="form__input-file">
            <input class="visually-hidden" type="file" id="photo2" name="jpg_img" value="">
            <label for="photo2">
                <span>+ Добавить</span>
            </label>
            <input type="hidden" name="file[about]" value="Аватар">
        </div>
    </div>
    <span class="form__error form__error--bottom">Пожалуйста, исправьте ошибки в форме.</span>
    <button type="submit" class="button">Зарегистрироваться</button>
    <a class="text-link" href="/">Уже есть аккаунт</a>
</form>


<!--<div class="form-container">-->
<!--    <form class="form-horizontal" method="post" action="/register_form" enctype="multipart/form-data">-->
<!--        <div class="form-group">-->
<!--            <label for="inputEmail3" class="col-sm-2 control-label">Логин</label>-->
<!--            <div class="col-sm-10">-->
<!--                <input type="text" class="form-control" id="inputEmail3" name="login" placeholder="Логин">-->
<!--            </div>-->
<!--        </div>-->
<!--        <div class="form-group">-->
<!--            <label for="inputPassword3" class="col-sm-2 control-label">Пароль</label>-->
<!--            <div class="col-sm-10">-->
<!--                <input type="password" class="form-control" id="inputPassword3" name="password" placeholder="Пароль">-->
<!--            </div>-->
<!--        </div>-->
<!--        <div class="form-group">-->
<!--            <label for="inputPassword4" class="col-sm-2 control-label">Пароль (Повтор)</label>-->
<!--            <div class="col-sm-10">-->
<!--                <input type="password" class="form-control" id="inputPassword4" name="password1" placeholder="Пароль">-->
<!--            </div>-->
<!--        </div>-->
<!--        <div class="form-group">-->
<!--            <div class="col-sm-offset-2 col-sm-10">-->
<!--                <button type="submit" class="btn btn-default">Зарегистрироваться</button>-->
<!--                <br><br>-->
<!--                Зарегистрированы? <a href="/">Авторизируйтесь</a>-->
<!--            </div>-->
<!--        </div>-->
<!--    </form>-->
<!--</div>-->
<!--https://echo.htmlacademy.ru-->