<h1>Запретная зона, доступ только авторизированному пользователю</h1>
<h2>Информация выводится из списка файлов</h2>
<table class="table table-bordered">
    <tr>
        <th>Название файла</th>
        <th>Фотография</th>
        <th>Действия</th>
    </tr>
    <?php foreach ($listf as $value) : ?>

    <tr>
        <td><?= $value->about?></td>
        <td><img src="<?= $value->file_name?>" alt="" height="150"></td>
        <td>
            <a href="">Удалить аватарку пользователя</a>
        </td>
    </tr>
    <?php endforeach; ?>
</table>